[project]
name = "cascade"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "huggingface-hub==0.36.0",
  "transformers==4.51.3",
  "numpy==2.2.3",
  "hydra-core==1.3",
  "hydra_colorlog==1.2.0",
  "torch==2.4.1",
  "datasets==3.0.1",
  "accelerate==0.34.2",
  "rouge-score==0.1.2",
  "scipy==1.14.1",
  "tensorboard==2.18.0",
  "deepspeed==0.15.4",
]

[dependency-groups]
dev = [
  "black>=25.11.0",
  "isort>=7.0.0",
  "pre-commit>=4.4.0",
  "ruff>=0.14.5",
]

[tool.uv]
index-url = "https://pypi.tuna.tsinghua.edu.cn/simple"

[tool.ruff]
target-version = "py310"
line-length = 120

[tool.ruff.lint]
select = ["E", "F", "W"]
ignore = ["E501"]

[tool.black]
line-length = 120
target-version = ["py310"]

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
