# @package eval.tofu.metrics.retain_Q_A_PARA_Prob

defaults:
  - /collator@collators: indexed
  - ../../data/datasets@datasets: TOFU_QA_retain_para
  # ^ get default dataset and generation config information

handler: probability
batch_size: ${eval.tofu.batch_size}
