# @package eval.tofu.metrics.wf_Q_A_Prob
defaults:
  - /collator@collators: indexed
  - ../../data/datasets@datasets: TOFU_QA_wf
  # ^ get default dataset and generation config information

handler: probability
batch_size: ${eval.tofu.batch_size}
